# -*- coding: utf-8 -*-
"""
IntentOS Cloud Cost Monitor

This module is responsible for estimating deployment costs and monitoring
cloud spending against a defined budget. It helps ensure that IntentOS
operates within its financial means.
"""

import logging
from typing import Any, Dict, List

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Placeholder for pricing data. In a real implementation, this would
# be fetched from the cloud provider's pricing API.
AWS_PRICING_DATA = {
    "vpc": 0.0, # VPCs are generally free
    "ecs_cluster": 0.0, # ECS clusters are free, you pay for resources
    "t3.micro": 0.0116, # Per hour
    "gp3_storage_gb": 0.08, # Per GB-month
}


class CostMonitor:
    """
    Monitors and estimates cloud costs for IntentOS.
    """

    def __init__(self, provider: str = 'aws', region: str = 'us-east-1'):
        """
        Initializes the cost monitor.

        :param provider: The cloud provider (e.g., 'aws').
        :param region: The cloud region (e.g., 'us-east-1').
        """
        self.provider = provider
        self.region = region
        self.budget = None
        logging.info(f"CostMonitor initialized for provider: {provider}, region: {region}")

    def load_budget(self, file_path: str = 'config/budget.yml') -> None:
        """
        Loads the budget configuration.

        # Example budget.yml:
        # monthly_spend_limit: 50.00 # USD
        """
        # Placeholder: In a real implementation, you'd load from a file.
        self.budget = {"monthly_spend_limit": 50.00}
        logging.info(f"Budget loaded: ${self.budget['monthly_spend_limit']}/month")

    def get_plan_cost_estimate(self, plan: Dict[str, Any]) -> Dict[str, float]:
        """
        Estimates the monthly cost of a deployment plan.

        :param plan: The deployment plan generated by the CloudOrchestrator.
        :return: A dictionary with cost breakdown and total.
        """
        logging.info("Estimating costs for the deployment plan...")
        total_monthly_cost = 0.0
        cost_breakdown = {}

        if self.provider == 'aws':
            for action in plan.get('actions', []):
                # Simple cost estimation based on placeholder data
                resource_type = action.get('type')
                cost = AWS_PRICING_DATA.get(resource_type, 0.0)

                # A more complex example for an EC2 instance or similar
                if 'instance_type' in action.get('details', {}):
                    instance_type = action['details']['instance_type']
                    cost = AWS_PRICING_DATA.get(instance_type, 0.0) * 24 * 30 # hourly to monthly

                cost_breakdown[action['name']] = cost
                total_monthly_cost += cost
        else:
            logging.warning(f"Cost estimation for '{self.provider}' is not implemented.")

        estimate = {
            "breakdown": cost_breakdown,
            "total_monthly_cost": round(total_monthly_cost, 2)
        }
        logging.info(f"Estimated monthly cost: ${estimate['total_monthly_cost']}")
        return estimate

    def check_current_spend(self) -> bool:
        """
        Checks the current monthly spend against the budget.

        :return: True if spend is within budget, False otherwise.
        """
        if not self.budget:
            logging.warning("Budget not loaded, cannot check current spend.")
            return True # Fail open

        # Placeholder: This would use the AWS Cost Explorer API in a real scenario
        current_spend = 35.00 # Dummy value
        limit = self.budget['monthly_spend_limit']

        logging.info(f"Current monthly spend: ${current_spend} (Budget: ${limit})")

        if current_spend > limit:
            logging.error(f"Budget exceeded! Spend: ${current_spend}, Limit: ${limit}")
            return False

        logging.info("Current spend is within budget.")
        return True

    def run_optimization_checks(self) -> List[Dict[str, Any]]:
        """
        Runs a series of checks to find cost optimization opportunities.

        :return: A list of suggested optimization actions.
        """
        logging.info("Running automated cost optimization checks...")
        suggestions = []

        # Placeholder for optimization logic.
        # In a real system, this would fetch metrics from a service like CloudWatch.

        # Rule 1: Check for underutilized ECS services during off-peak hours.
        # Simulating low CPU usage at night.
        avg_cpu_last_4_hours = 15.0 # Simulating 15% average CPU
        num_of_instances = 2

        if avg_cpu_last_4_hours < 20.0 and num_of_instances > 1:
            estimated_savings = AWS_PRICING_DATA.get('t3.micro', 0.0) * 24 * 30 * (num_of_instances - 1)
            suggestion = {
                "action": "scale_down",
                "resource_id": "intentos-main-cluster-service",
                "details": f"Average CPU is {avg_cpu_last_4_hours}%, which is below the 20% threshold.",
                "proposed_change": {
                    "property": "instance_count",
                    "current_value": num_of_instances,
                    "new_value": 1
                },
                "estimated_monthly_savings": round(estimated_savings, 2)
            }
            suggestions.append(suggestion)
            logging.info(f"Found optimization: Scale down. Save ~${suggestion['estimated_monthly_savings']}/month.")

        if not suggestions:
            logging.info("No immediate cost optimization opportunities found.")

        return suggestions
